config:
  limits.cpu: "4"
  limits.memory: 8GiB
  security.secureboot: "false"

  cloud-init.user-data: |
    #cloud-config

    ssh_keys:
      ed25519_private: |
        ${SSH_HOST_PRIVATE_KEY}
      ed25519_public: ${SSH_HOST_PUBLIC_KEY}

    ssh_deletekeys: false
    
    users:
      - name: starter-home
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        ssh_authorized_keys:
          - ${SSH_PUBLIC_KEY}

    package_update: true
    packages:
      - openssh-server
      - python3

    write_files:
      - path: /etc/ssh/sshd_config.d/70-disable-non-key-auth.conf
        permissions: '0644'
        content: |
          PasswordAuthentication no
          KbdInteractiveAuthentication no
          UsePAM yes
      
    runcmd:
      - systemctl enable --now ssh

devices:
  root:
    type: disk
    path: /
    pool: default
    size: 10GiB

  eth0:
    name: eth0
    network: incusbr0
    type: nic
    ipv4.address: 10.56.24.100

  http:
    type: proxy
    listen: tcp:10.0.2.15:80
    connect: tcp:0.0.0.0:8080
    nat: "true"

  # ssh:
  #   type: proxy
  #   listen: tcp:0.0.0.0:3333
  #   connect: tcp:127.0.0.1:3333

  host-storage:
    type: disk
    source: /home/isaac/starter-home/host-storage
    path: /host-storage
    required: true
